name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Lint
        run: yarn rw lint

      - name: Build
        run: yarn rw build

      - name: Test
        run: yarn rw test api --db-push=false --no-watch
